### ISSUE TITLE
Reduce number of database connects

### ISSUE THREAD

**Issue by TheComamba** [TheComamba/LoreCore#29]
The functions writing to database currently do so entry by entry, and reconnect every time.
I suggest making them expect a vector of EntityColumn etc.

**Comment by TheComamba** [comment]
Should probably only be tackled once branch api-function-to-read-database is merged.

**Comment by Luichang** [comment]
8021574 took care of the database connections now taking a vec and thus can add multiple of the same table to the database using a single connection
